Create initial contracts and methods for HTTP device onboarding
timstewartm/azure-iot-sdk-csharp pull request #1
Opened 2023-08-10 21:35 UTC by timstewartm

Work in progress

2023-10-24 21:11 UTC, kagoyal requested changes

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/samples/how to guides/TpmSample/Program.cs
> +namespace Microsoft.Azure.Devices.Provisioning.Client.Samples
namespace Microsoft.Azure.Devices.Discovery.Client.Samples

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/samples/how to guides/TpmSample/DiscoveryDeviceClientSample.cs
> +    /// Demonstrates how to register a device with the device provisioning service using a certificate, and then
fix comment

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +    /// Allows devices to use the Device Provisioning Service.
Discovery

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +        /// Creates an instance of the Device Provisioning Client.
Please fix all occurrences of provisioning service in comments

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +            return new DiscoveryDeviceClient(globalDeviceEndpoint, securityProvider, transport);
As only TPM security provider is allowed right now, let's put the check here when creating client

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +        /// Gets challenge string to decrypt to onboard device
nit: Issues challenge to authenticate the given device

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +        /// <returns></returns>
returns nonce challenge

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportException.cs
> +    /// Represents errors reported by the Provisioning Transport Handlers.
Please fix all comments - Discovery Transport Handlers

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportException.cs
> +        private const string IsTransientValueSerializationStoreName = "ProvisioningTransportException-IsTransient";
DiscoveryTransportException

2023-10-24 21:11 UTC, kagoyal commented on common/src/Logging.ProvisioningTransport.Common.cs
> +        public static void OnboardDevice(
Why do we need this change? This is also inside provisioning amqp layer? Is file just wrongly named?

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +        /// Gets challenge string to decrypt to onboard device
fix comment

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryDeviceClient.cs
> +        /// <exception cref="NotSupportedException">Security provider must be TPM</exception>
Let's fail when creating client itself as mentioned above

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportHandler.cs
> +        public RemoteCertificateValidationCallback RemoteCertificateValidationCallback { get; set; }
not used, remove this

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/OnboardingInfo.cs
> +    /// Holds information returned from the getOnboardingInfo endpoint
/// Holds information returned from the getOnboardingInfo **request**

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/OnboardingInfo.cs
> +        /// <summary>
add new line before summary

2023-10-24 21:11 UTC, kagoyal commented on discovery/transport/http/src/DiscoveryTransportHandlerHttp.cs
> +using Newtonsoft.Json.Linq;
remove all unused usings

2023-10-24 21:11 UTC, kagoyal commented on discovery/transport/http/src/DiscoveryTransportHandlerHttp.cs
> +
remove the comment here

2023-10-24 21:11 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportHandler.cs
> +        public virtual Task<string> IssueChallengeAsync(DiscoveryTransportIssueChallengeRequest request, CancellationToken cancellationToken)
Please copy summary from generated code - 
            /// Issue TPM Challenge. Will return an encrypted nonce, that can be used to
            /// sign a SAS Token for the GetOnboardingInfo request.

2023-10-24 21:11 UTC, kagoyal commented on discovery/transport/http/src/DiscoveryTransportHandlerHttp.cs
> +        private string GenerateCSR(RSA rsa, string deviceId)
please add summary

2023-10-24 21:11 UTC, kagoyal commented on discovery/transport/http/src/Logging.DiscoveryTransport.Http.cs
> +    // d209b8a1-2e02-5724-f341-677227d0ed22
can you check if these GUIDs have to be new/different for discovery.
Also let's test we are getting logs once logging is enabled

2023-10-24 21:11 UTC, kagoyal commented on e2e/test/E2ETests.csproj
> -    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net6.0;net5.0;netcoreapp3.1;netcoreapp2.1.30;net472;net451</TargetFrameworks>
Let's not change this condition in e2etests project

2023-10-24 21:11 UTC, kagoyal commented on e2e/test/config/TestConfiguration.Discovery.cs
> +            public static string ConnectionString => GetValue("PROVISIONING_CONNECTION_STRING");
DISCOVERY_CONNECTION_STRING?

2023-10-24 21:11 UTC, kagoyal commented on provisioning/device/src/CommonExtensions.cs
> +namespace Microsoft.Azure.Devices.Provisioning.Client
why this namespace change?
Let's not change it

2023-10-24 21:11 UTC, kagoyal commented on provisioning/device/src/DeviceOnboardingResult.cs
> +        /// <summary> The status of the onboarding process.Possible values include:
newline after this

2023-10-24 22:19 UTC, timstewartm commented on e2e/test/E2ETests.csproj
> -    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net6.0;net5.0;netcoreapp3.1;netcoreapp2.1.30;net472;net451</TargetFrameworks>
The discovery code is not compatible with the other frameworks.

2023-11-02 22:35 UTC, timstewartm commented on e2e/test/E2ETests.csproj
> -    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">net6.0;net5.0;netcoreapp3.1;netcoreapp2.1.30;net472;net451</TargetFrameworks>
Will evaluate dependencies and take this in future PR

2023-11-02 22:54 UTC, kagoyal approved these changes

2023-11-02 23:29 UTC, merged