Add .NET 8 support
timstewartm/azure-iot-sdk-csharp pull request #9
Opened 2024-03-20 23:31 UTC by ayeshap20

2024-04-09 21:10 UTC, kagoyal requested changes
Let's discuss exception code you have to comment here.

2024-04-09 21:10 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportException.cs
> +        ///// </summary>
what is difference between commented and uncommented  code? Looks exactly same.
Also delete any commented code if required.

2024-04-09 21:10 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportException.cs
>          protected DiscoveryTransportException(SerializationInfo info, StreamingContext context)
can you share exact warning that was coming? do we need to add new exception now? @timstewartm  can you please help here

2024-04-09 21:10 UTC, kagoyal commented on shared/src/TlsVersions.cs
> +#pragma warning disable SYSLIB0039 // .NET8: TLS1.0 and 1.1 are obsolete
Let's not disable this warning.
Instead remove usage of TLS1.0 and 1.1

2024-04-15 22:51 UTC, ayeshap20 commented on discovery/device/src/DiscoveryTransportException.cs
>          protected DiscoveryTransportException(SerializationInfo info, StreamingContext context)
The warning is around serializing the exception:

SYSLIB0051:'Exception.Exception(SerializationInfo, StreamingContext)' is obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.' (
https://aka.ms/dotnet-warnings/SYSLIB0051)

2024-04-15 22:51 UTC, ayeshap20 commented on shared/src/TlsVersions.cs
> +#pragma warning disable SYSLIB0039 // .NET8: TLS1.0 and 1.1 are obsolete
Fixed in the latest iteration

2024-04-15 22:52 UTC, ayeshap20 commented on discovery/device/src/DiscoveryTransportException.cs
> +        ///// </summary>
Wanted to comment out the method since it's resulting the serialization error that I mentioned in the next comment.

2024-04-15 22:59 UTC, ayeshap20 commented
> Let's discuss exception code you have to comment here.

2024-04-15 23:18 UTC, kagoyal commented on discovery/device/src/DiscoveryTransportException.cs
>          protected DiscoveryTransportException(SerializationInfo info, StreamingContext context)
Thanks for context.
First, remove constructor wherever possible. Where you cannot -
Can you add this tag     [Obsolete(DiagnosticId = "SYSLIB0051")]  for better readability.

2024-04-15 23:35 UTC, ayeshap20 commented on discovery/device/src/DiscoveryTransportException.cs
>          protected DiscoveryTransportException(SerializationInfo info, StreamingContext context)
> Thanks for context. First, remove constructor wherever possible. Where you cannot - Can you add this tag [Obsolete(DiagnosticId = "SYSLIB0051")] for better readability.

Fixed

2024-04-16 00:44 UTC, kagoyal approved these changes

2024-04-16 16:20 UTC, merged